export const posts = [
    {
        title: "My First Blog Post",
        author: "Kitten",
        date: new Date(2026, 4, 5, 19, 39, 49),
        modifiedDate: new Date(2026, 4, 5, 19, 39, 49),
        filename: "post1.md",
        tags: ["blog", "web development", "typescript", "markdown"],
        searchWords: ["typescript notes", "web development", "github pages", "markdown blog", "web dev experiments"],
        excerpt: "An introductory post exploring web development, TypeScript, and the setup of a lightweight blog using Markdown and GitHub Pages.",
        readingTime: "1 min read",
        hash: "fe07827968b58d486123963a74a73409d6c1c770bb8b00d73e43881125645459"
    },
    {
        title: "LoRA and QLoRA Explained: Principles and Memory Optimization Techniques",
        author: "Kitten",
        date: new Date(2026, 4, 5, 19, 39, 59),
        modifiedDate: new Date(2026, 4, 5, 19, 39, 59),
        filename: "post10.md",
        tags: ["lora", "qlora", "fine-tuning", "optimization", "llm"],
        searchWords: ["low-rank adaptation", "quantized lora", "parameter efficient fine-tuning", "gpu memory optimization", "nf4 quantization"],
        excerpt: "Explore how LoRA and QLoRA optimize large language model fine-tuning through low-rank decomposition and 4-bit quantization to significantly reduce GPU memory requirements.",
        readingTime: "3 min read",
        hash: "8b37832c86dbc99c9066e70d2226cd0cef6a831c13b2aac5bfc52b4a8bd655f3"
    },
    {
        title: "JD Interviewer Follow-up: “Your RAG System Retrieved the CEO’s Salary for a Regular Employee—How Do You Handle Permissions?”",
        author: "Kitten",
        date: new Date(2026, 4, 5, 19, 40, 13),
        modifiedDate: new Date(2026, 4, 5, 19, 40, 13),
        filename: "post11.md",
        tags: ["rag", "security", "vector database", "ai architecture", "permissions"],
        searchWords: ["rag permission control", "pre-filtering vs post-filtering", "vector database security", "enterprise rag implementation", "data access control"],
        excerpt: "Learn why post-filtering fails in enterprise RAG systems and how to implement secure, efficient permission control using metadata pre-filtering.",
        readingTime: "5 min read",
        hash: "0068d82e8a9ca2a88ff98ed030bf8091fd6f7408736f0148384e8b1d331e7366"
    },
    {
        title: "Context-aware AI that Adapts to the Audience",
        author: "Kitten",
        date: new Date(2026, 4, 5, 19, 40, 23),
        modifiedDate: new Date(2026, 4, 5, 19, 40, 23),
        filename: "post12.md",
        tags: ["ai", "context-aware", "architecture", "rag", "prompt-engineering"],
        searchWords: ["context-aware ai", "rag architecture", "dynamic prompt engineering", "audience modeling", "ai system design"],
        excerpt: "Explore the architecture of context-aware AI systems, covering dynamic prompt composition, advanced RAG pipelines, and techniques for tailoring AI responses to specific audiences.",
        readingTime: "4 min read",
        hash: "dc78ba7ac4acc365f2530ac437d72ddf65539509681522624272eeaac945ea24"
    },
    {
        title: "Model Context Protocol (MCP): A Systems-Level Approach to Context-Aware AI",
        author: "Kitten",
        date: new Date(2026, 4, 5, 19, 40, 36),
        modifiedDate: new Date(2026, 4, 5, 19, 40, 36),
        filename: "post13.md",
        tags: ["mcp", "ai", "llms", "architecture", "context"],
        searchWords: ["model context protocol", "context orchestration", "ai agents", "context graph", "llm design"],
        excerpt: "Learn how the Model Context Protocol (MCP) provides a standardized, systems-level framework for managing context injection, retrieval, and orchestration in AI agents.",
        readingTime: "3 min read",
        hash: "656f756488aa9976a50b140499d468b7ee75576f274a59fbbd1d540ac9e7990e"
    },
    {
        title: "A/B Testing LLM Outputs in Production Systems",
        author: "Kitten",
        date: new Date(2026, 4, 5, 19, 40, 46),
        modifiedDate: new Date(2026, 4, 5, 19, 40, 46),
        filename: "post14.md",
        tags: ["llm", "ab testing", "production", "machine learning"],
        searchWords: ["llm evaluation", "ab testing llm", "llm production architecture", "llm-as-a-judge", "llm monitoring"],
        excerpt: "Learn how to design and implement robust A/B testing pipelines for LLM outputs, covering traffic routing, evaluation strategies, and production monitoring.",
        readingTime: "4 min read",
        hash: "f8365bfdd56ecb379a9384c2af08e20a9c1eba97ecaadb08eab81b79b8f4fd8e"
    },
    {
        title: "*Designing Data-Intensive Applications* — Applied to Modern AI & RAG Systems",
        author: "Kitten",
        date: new Date(2026, 4, 6, 15, 5, 26),
        modifiedDate: new Date(2026, 4, 8, 20, 2, 8),
        filename: "post15.md",
        tags: ["ai", "rag", "distributed-systems", "data-engineering"],
        searchWords: ["rag architecture", "distributed systems in ai", "vector database principles", "llm data contracts", "semantic consistency"],
        excerpt: "Explore how fundamental distributed systems principles from Designing Data-Intensive Applications apply to building scalable and consistent RAG and AI architectures.",
        readingTime: "4 min read",
        hash: "e9bee3811597b6bf3a3fe5007ae7bdec0eb392b49732dfec25540f630a8ec6fa"
    },
    {
        title: "pgvector vs Milvus vs Qdrant: Filtering, Permissions, and What Actually Matters in Production RAG",
        author: "Kitten",
        date: new Date(2026, 4, 8, 20, 2, 22),
        modifiedDate: new Date(2026, 4, 8, 20, 2, 22),
        filename: "post16.md",
        tags: ["pgvector", "milvus", "qdrant", "rag", "vector-databases"],
        searchWords: ["vector database comparison", "rag filtering techniques", "pgvector vs milvus", "vector search security", "production rag implementation"],
        excerpt: "Evaluate the trade-offs between pgvector, Milvus, and Qdrant regarding filtering, security, and performance for building reliable, enterprise-grade RAG systems.",
        readingTime: "5 min read",
        hash: "78376ae858f973564cfc7a65b6630201aebb97a1a0a476e93036afdcfa90cd8e"
    },
    {
        title: "Production RAG Architecture: Why Real Systems Use Multiple Databases",
        author: "Kitten",
        date: new Date(2026, 4, 11, 10, 32, 7),
        modifiedDate: new Date(2026, 4, 11, 10, 32, 7),
        filename: "post17.md",
        tags: ["rag", "architecture", "databases", "scalability"],
        searchWords: ["production rag", "rag architecture", "vector databases", "distributed retrieval", "scaling rag"],
        excerpt: "Learn why scaling RAG systems requires moving beyond single-database prototypes toward a distributed architecture of specialized storage layers for production-grade performance.",
        readingTime: "5 min read",
        hash: "da0615f7e697b1f5850ccd31c81ce53fa0371259309ab2e1e164d7337e03e936"
    },
    {
        title: "Rerankers in Production RAG: The Missing Layer Between Vector Search and LLM Quality",
        author: "Kitten",
        date: new Date(2026, 4, 11, 12, 11, 41),
        modifiedDate: new Date(2026, 4, 11, 12, 11, 41),
        filename: "post18.md",
        tags: ["rag", "reranking", "vector search", "llm"],
        searchWords: ["rag precision", "reranker vs embedding", "two stage retrieval", "cross-encoders", "production rag"],
        excerpt: "Learn how a two-stage retrieval architecture using rerankers improves RAG precision by bridging the gap between vector search recall and true query relevance.",
        readingTime: "7 min read",
        hash: "2b16d0095e588cab1782081aea5498149454a226224e16b6a492dfbc4ad43f31"
    },
    {
        title: "SSE vs WebSockets in Production Systems: Streaming Architecture for Modern AI and Real-Time Applications",
        author: "Kitten",
        date: new Date(2026, 4, 11, 14, 5, 51),
        modifiedDate: new Date(2026, 4, 11, 14, 5, 51),
        filename: "post19.md",
        tags: ["sse", "websockets", "streaming", "architecture"],
        searchWords: ["sse vs websockets", "real-time streaming", "server-sent events", "web socket architecture", "ai token streaming"],
        excerpt: "Compare SSE and WebSockets to understand when to use unidirectional vs bidirectional streaming for AI-driven applications and real-time systems.",
        readingTime: "8 min read",
        hash: "205692abe4b70b4131bb25c860b693b76c3cb77bc10c3349b2fce1755c9a8cd9"
    },
    {
        title: "Untitled Post",
        author: "Kitten",
        date: new Date(2026, 4, 5, 19, 40, 56),
        modifiedDate: new Date(2026, 4, 5, 19, 40, 56),
        filename: "post2.md",
        tags: ["json", "metadata", "blog", "automation"],
        searchWords: ["json metadata generator", "blog post automation", "structured blog metadata"],
        excerpt: "A technical specification for generating structured JSON metadata, including tags, search keywords, and professional excerpts for blog posts.",
        readingTime: "1 min read",
        hash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    },
    {
        title: "Fitting Maximum Signal into a Limited Context Window",
        author: "Kitten",
        date: new Date(2026, 4, 12, 21, 37, 7),
        modifiedDate: new Date(2026, 4, 12, 21, 47, 8),
        filename: "post20.md",
        tags: ["llm", "context engineering", "prompt optimization", "ai"],
        searchWords: ["context window optimization", "llm performance", "large codebase ai", "token management", "prompt engineering"],
        excerpt: "Learn how to maximize signal-to-noise ratio in LLM prompts using context engineering, memory hierarchies, and structural compression for large codebases.",
        readingTime: "6 min read",
        hash: "8072dbb24c127161e44dc137edacf134863959d2b0542bd228506c6f443799cf"
    },
    {
        title: "Designing Robust Prompts for RAG Systems (Eliminating Hallucinations)",
        author: "Kitten",
        date: new Date(2026, 4, 5, 19, 41, 56),
        modifiedDate: new Date(2026, 4, 5, 19, 41, 56),
        filename: "post3.md",
        tags: ["rag", "prompt engineering", "llm", "hallucinations"],
        searchWords: ["rag prompt engineering", "reduce llm hallucinations", "retrieval augmented generation", "prompt design strategies", "ai prompt optimization"],
        excerpt: "Learn how to design robust prompts for RAG systems to eliminate hallucinations by enforcing strict document adherence and effective refusal strategies.",
        readingTime: "3 min read",
        hash: "03af5d4294b559258e34c7672061299a59ea2e87cec0bc9fe483584c7bb4eda6"
    },
    {
        title: "Same Chunking, But 10× Better RAG? The Answer Is Hidden Here!",
        author: "Kitten",
        date: new Date(2026, 4, 5, 19, 42, 8),
        modifiedDate: new Date(2026, 4, 5, 19, 42, 8),
        filename: "post4.md",
        tags: ["rag", "chunking", "llm", "nlp"],
        searchWords: ["rag chunking strategies", "semantic chunking", "text splitting", "retrieval augmented generation", "llm optimization"],
        excerpt: "Learn how optimized text chunking strategies like semantic and sliding window can significantly improve RAG retrieval accuracy and reduce hallucinations.",
        readingTime: "5 min read",
        hash: "4b721ef3c8d9e40482dde683e5d8fb371437989fdbb8000da6cdaa4baf43cd28"
    },
    {
        title: "Elasticsearch BBQ: A Textbook Case of “Overtaking on a Curve” in Vector Search",
        author: "Kitten",
        date: new Date(2026, 4, 5, 19, 42, 20),
        modifiedDate: new Date(2026, 4, 5, 19, 42, 20),
        filename: "post5.md",
        tags: ["elasticsearch", "vector search", "quantization", "bbq"],
        searchWords: ["elasticsearch bbq", "vector search optimization", "raBitQ algorithm", "hnsw quantization", "memory efficient vector search"],
        excerpt: "Discover how Elasticsearch leverages BBQ (Better Binary Quantization) to achieve up to 95% memory reduction in vector search while maintaining high accuracy.",
        readingTime: "4 min read",
        hash: "777c350482be6c6f5eb0fef52b5ca8bf7e65f757faf917ec455c0a1204b2932c"
    },
    {
        title: "HNSW_SQ for Efficient Indexing: How to Balance RAG Speed, Recall, and Cost at the Same Time",
        author: "Kitten",
        date: new Date(2026, 4, 5, 19, 42, 30),
        modifiedDate: new Date(2026, 4, 5, 19, 42, 30),
        filename: "post6.md",
        tags: ["vector database", "hnsw", "scalar quantization", "milvus", "rag"],
        searchWords: ["hnsw_sq", "vector indexing", "scalar quantization", "milvus performance", "rag optimization", "vector compression"],
        excerpt: "Learn how HNSW_SQ optimizes vector retrieval by combining HNSW with Scalar Quantization to balance search speed, recall, and memory costs in RAG pipelines.",
        readingTime: "6 min read",
        hash: "8c0b7ac7a4cb72a0498f6ff54969f85fb52db40f4e28af8ffb320bd408b2b24d"
    },
    {
        title: "Code Interpreter Security in RAG Systems: From Sandbox Design to Production Implementation",
        author: "Kitten",
        date: new Date(2026, 4, 5, 19, 42, 41),
        modifiedDate: new Date(2026, 4, 5, 19, 42, 41),
        filename: "post7.md",
        tags: ["rag", "security", "sandboxing", "ai-agents"],
        searchWords: ["rag security", "code interpreter sandbox", "docker isolation", "e2b", "python execution security"],
        excerpt: "Explore secure implementation strategies for code interpreters in RAG systems, covering risks of direct execution and approaches like Docker isolation and cloud sandboxes.",
        readingTime: "3 min read",
        hash: "964c35d5ddaffe5653ada4fde8ffd39fc41a4cd790e077898e466b6ffd9804f0"
    },
    {
        title: "Operating RAG Systems: A Complete Badcase Feedback Loop from Collection to Fix",
        author: "Kitten",
        date: new Date(2026, 4, 5, 19, 42, 53),
        modifiedDate: new Date(2026, 4, 5, 19, 42, 53),
        filename: "post8.md",
        tags: ["rag", "mlops", "llm", "observability"],
        searchWords: ["rag error detection", "llm hallucination fixes", "retrieval failure analysis", "rag feedback loop", "ai system monitoring"],
        excerpt: "Learn how to implement a 6-step feedback loop to detect, classify, and fix common RAG failures like retrieval errors, hallucinations, and routing mistakes.",
        readingTime: "3 min read",
        hash: "658132e20ff7fd180c20a6ec36e1aea7488344b99d3ff51de7a6c45cee953898"
    },
    {
        title: "Distributed Locks with Redis: What Happens If Redis Crashes?",
        author: "Kitten",
        date: new Date(2026, 4, 5, 19, 43, 4),
        modifiedDate: new Date(2026, 4, 5, 19, 43, 4),
        filename: "post9.md",
        tags: ["redis", "distributed-locks", "system-design", "backend"],
        searchWords: ["redis master-slave failover", "redlock algorithm", "distributed locking reliability", "zookeeper vs redis", "distributed systems consistency"],
        excerpt: "Explore the critical risks of lock loss during Redis master-slave failover and evaluate robust alternatives like Redlock and Zookeeper for distributed locking.",
        readingTime: "2 min read",
        hash: "6e02b0fa24612ee1579c8f24750da0653c97689e4513d93b3a1ef8629941971c"
    }
];
